### ISSUE TITLE
Add Ripple Effect Cursor Component to the Library

### ISSUE THREAD

**Issue by ZeeshanMukhtar1** [ui-layouts/cursify#3]
#### **Description:**
Create and integrate a **Ripple Effect Cursor** component into the **Cursify** library. The Ripple Effect Cursor will generate expanding and fading ripple effects at the cursor's position during movement, providing a sleek and interactive user experience.

#### **Requirements:**

1. **Component Implementation**:
   - Create a new component file: `RippleCursor.tsx` under `src/components/cursor/RippleCursor/`.
   - Use **React** and **Framer Motion** to achieve smooth animations.
   - Ensure the ripples originate from the cursor’s position and fade out as they expand.

2. **CSS Styling**:
   - Create a `RippleCursor.css` file in the same directory.
   - Use this file for defining the styles of the ripple effect, such as color, size, and fading animation.

3. **Reusable Component**:
   - Export the `RippleCursor` as a standalone, reusable component.
   - It should follow the structure and best practices used in existing cursors like `BlobCursor` or `NeonCursor`.

4. **Folder Structure**:
   ```
   src/components/cursor/RippleCursor/
   ├── RippleCursor.tsx
   ├── RippleCursor.css
   ```

#### **Acceptance Criteria:**

- The RippleCursor component should:
  1. Render smoothly with no performance issues.
  2. Work seamlessly with any React or Next.js application using the library.
  3. Follow the existing folder structure and coding conventions of the project.
---

**Comment by ZeeshanMukhtar1** [comment]
@durgeshbachhav , @akshaymemane  
Kindly assign this issue to me. I am excited to contribute to this project and look forward to enhancing the library with this new Cursor!

**Comment by akshaymemane** [comment]
> @durgeshbachhav , @akshaymemane Kindly assign this issue to me. I am excited to contribute to this project and look forward to enhancing the library with this new Cursor!

If you want you can create a PR and add screenshots or video of the output.

**Comment by ZeeshanMukhtar1** [comment]
Hi @akshaymemane , the PR is ready with all requested changes, including screenshots; kindly review and merge. Thank you!
